"""ADR-0037 Stage-3b — the tree-synthesis Layer-2 stage (bucket-B signal folds).

Folding a lane mirror to a Tier-1 structural read (ADR-0036) leaves a **bucket-B**
tail: a genuine phase-parse gap where the clause survives only in the card's oracle
text (phase emits NO typed node the signal lane could read). Neither existing
Layer-2 stage can fill it:

* :mod:`overlay_corrections` (bucket b) only DECORATES existing concept-nodes; its
  substrate-purity invariant forbids ADDING a node.
* :mod:`dropped_clauses` (bucket c) synthesizes onto the compat ``Card``
  (``ir_for``),
  which the Signal lanes never read.

This stage ADDS a synthetic :class:`ConceptNode` to the crosswalk tree for such a
gap. Each arm reads the whole-card oracle (``tree.oracle``) with a regex **once**
and, for a genuine gap, emits a synthetic concept-node whose ``concept`` / ``scope``
/ ``subject`` the lane reads structurally. The synthetic node carries a
:class:`SynthesizedNode` marker in its ``.node`` slot — provenance (the arm id + a
description), NOT phase substrate.

**Signal-path-only.** :func:`apply_tree_synthesis` runs AFTER
:func:`overlay_corrections.apply_overlay_corrections` in the
``extract_crosswalk_signals`` path ONLY — never in ``compat_card``. So the compat
Card and the five the compat-Card consumer views are unaffected: a bucket-B fold moves
*signals* and nothing else (the signal-diff is the whole gate).

**The purity invariant relaxes, precisely (see :mod:`_substrate_purity`).** It
changes from "the L1 node fingerprint is unchanged" to "every *phase* L1 node
present before is present after with the same identity; :class:`SynthesizedNode`
additions are allowed." ``l1_nodes`` filters out synthetic nodes, so the phase
fingerprint is still asserted exactly — adding a node is legal ONLY here and ONLY
as a tagged synthetic node.

**Convergence-tracked.** Each arm is keyed by id (:data:`SYNTHESIS_ARM_IDS`) so the
input-side convergence check retires it when phase begins parsing the clause
(ADR-0035 shrinking bridge). A synthesis arm is a bridge, not a permanent home.

**ADR-0038 retired the ``synth_*`` marker namespace.** A genuine dropped-rider
gap — phase emits NO residue node at all for the clause (``suspect_makers``'s
Case of the Stashed Skeleton: the "suspect it" rider vanishes from the token-
creation effect entirely) — stays a synthesis arm per ADR-0037 (re-decoration
has no node to re-decorate). But the arm now emits the REAL concept name
(``"suspect"``, not ``"synth_suspect_makers"``), so the lane reads it through
its ordinary typed ``effect_concepts(...)`` arm — no ``synth_<key>`` marker
special-case in the lane at all. Only a card whose Unimplemented clause DOES
survive as a node is eligible for the other ADR-0038 mechanism instead
(:mod:`recovery`'s re-decoration, keyed off an allowlisted grammar token).
"""

from __future__ import annotations

from mtg_utils._card_ir._substrate_purity import SynthesizedNode
from mtg_utils._card_ir.crosswalk import has_filter_property
from mtg_utils._card_ir.tree_synthesis._registry import (
    SYNTHESIS_ARM_IDS,
    apply_tree_synthesis,
    synthesize_nodes,
)
from mtg_utils._card_ir.tree_synthesis.combat import (
    ATTACK_TRIGGER_EVENTS,
    RAID_CONDITION_TAGS,
    _arm_base_power_ref_conjunctive,
    _arm_base_pt_have_become,
    _arm_base_pt_is_a_type_with,
    _arm_base_pt_mass_where_x,
    _arm_evasion_self,
    _arm_exalted_lone_attacker,
    _arm_firebending_matters,
    _arm_power_matters,
    _arm_pump_makers,
    _arm_station_matters,
    attack_raid_condition,
    has_attack_trigger,
    has_attacking_you_effect,
    has_structural_base_power_ref,
    has_structural_base_pt_set,
    has_structural_exert_matters,
    has_structural_firebending_grant,
    has_structural_pump_makers,
    has_structural_station_charge,
    has_structural_station_reference,
    has_structural_toughness_combat,
)
from mtg_utils._card_ir.tree_synthesis.control_stax import (
    _arm_cant_block_grant,
    _arm_color_hoser,
    _arm_dont_own,
    _arm_legend_rule_off,
    _arm_opponent_counter_grant,
    _arm_opponent_exile_matters,
    _arm_sacrifice_protection,
    _arm_stax_taxes,
    _arm_superfriends_matters,
    _arm_symmetric_stax,
    _arm_targeting_matters,
    _arm_void_warp_makers,
    _stax_structural_walk,
    has_structural_cant_block_grant,
    has_structural_color_hoser,
    has_structural_legend_rule_off,
    has_structural_opponent_counter_grant,
    has_structural_stax_taxes,
    has_structural_superfriends,
    has_structural_symmetric_stax,
    has_structural_targeting_matters,
)
from mtg_utils._card_ir.tree_synthesis.counters_tokens import (
    _arm_counter_distribute,
    _arm_keyword_counter,
    _arm_poison_matters,
    _arm_proliferate_matters,
    _arm_proliferate_remove_cost,
    _arm_self_counter_grow,
    _arm_self_power_scale,
    _mirror_token_maker_type_subjects,
    has_structural_counter_distribute,
    has_structural_keyword_counter,
    has_structural_proliferate,
    has_structural_self_counter_grow,
    structural_token_maker_type_subjects,
)
from mtg_utils._card_ir.tree_synthesis.death_life import (
    _arm_life_payment_insurance,
    _double_triggers_creature_dying,
    _has_structural_lifegain,
    _is_creature_death_subject,
    _is_death_payoff_effect,
    _is_self_return_effect,
    _is_shuffle_back_effect,
    creature_death_condition,
    has_gain_life_amplifier,
    has_high_life_total_payoff,
    has_life_gained_this_turn,
    has_life_gained_trigger,
    has_selfloss_engine,
    has_structural_life_payment_insurance,
    has_trigger_draw_bleed,
    mass_death_amount,
)
from mtg_utils._card_ir.tree_synthesis.mana_ramp_lands import (
    _arm_extra_land_drop,
    _arm_historic_matters,
    _arm_land_fetch_ramp,
    _arm_ramp_dropped_add_mana_clause,
    _arm_ramp_grant_unimplemented_body,
    _arm_tutor,
    _arm_unspent_mana,
    _arm_untap_engine,
    _iter_untap_targets,
    _matches_add_mana_clause,
    has_structural_extra_land_drop,
    has_structural_ramp_grant_mana,
    has_structural_tutor,
    has_structural_unspent_mana,
    has_structural_untap_engine,
    structural_land_fetch_split,
    structural_untap_scope,
    structural_untap_subject,
)
from mtg_utils._card_ir.tree_synthesis.mechanics_misc import (
    _arm_celebration_matters,
    _arm_clue_matters,
    _arm_coven_matters,
    _arm_crimes_matter,
    _arm_curse_matters,
    _arm_outlaw_matters,
    _arm_suspect_matters,
    _arm_suspend_matters,
    _arm_token_subtype_own_ref,
    has_structural_clue_matters,
    has_structural_crimes_matter,
    has_structural_curse_matters,
    has_structural_outlaw,
    has_structural_suspend_matters,
)
from mtg_utils._card_ir.tree_synthesis.spells_casting import (
    _SPELLCAST_TRIGGER_RX,
    CAST_TRIGGER_EVENTS,
    _arm_ability_copy,
    _arm_arcane_matters,
    _arm_becomes_target_src_opp,
    _arm_convoke_matters,
    _arm_creature_cast_trigger,
    _arm_exhaust_matters,
    _arm_flash_matters,
    _arm_keyword_soup_same_true,
    _arm_lessons_matter,
    _arm_miracle_grant,
    _arm_noncombat_damage_payoff,
    _arm_opponent_cast_matters,
    _arm_per_target_payoff,
    _arm_spellcast_matters,
    _matches_spellcast_idiom,
    has_permanent_recast,
    has_structural_arcane,
    has_structural_creature_cast_trigger,
    has_structural_lessons_matter,
    has_structural_miracle_grant,
    has_structural_opponent_cast_matters,
    has_structural_spellcast,
)
from mtg_utils._card_ir.tree_synthesis.types_tribal import (
    _ANTHEM_PUMP_MODS,
    _arm_animate_artifact,
    _arm_color_change,
    _arm_island_matters,
    _arm_keyword_tribe,
    _arm_keyword_tribe_any,
    _arm_land_creatures_dynamic_animate,
    _arm_manland,
    _arm_multicolor_matters,
    _arm_snow_matters,
    _arm_type_change,
    _arm_type_matters,
    _arm_typed_anthem_multi,
    _arm_vehicles_matter,
    has_structural_land_creatures_animate,
    has_structural_manland,
    has_structural_multicolor_matters,
    has_structural_snow_matters,
    has_structural_type_change,
    has_structural_vehicles_matter,
    structural_keyword_subjects,
    structural_type_subjects,
)
from mtg_utils._card_ir.tree_synthesis.value_engines import (
    _EACH_DRAW_RECIPIENTS,
    ETB_TRIGGER_EVENTS,
    PER_TURN_CONSTRAINT_TAGS,
    _arm_b13_node_anchor,
    _arm_b13_raw_anchor,
    _arm_big_hand_makers,
    _arm_big_hand_matters,
    _arm_coin_flip_payoff,
    _arm_connive_makers,
    _arm_dice_makers,
    _arm_discover_makers,
    _arm_fight_makers,
    _arm_group_hug_draw,
    _arm_kill_engine,
    _arm_theft_makers,
    _has_repeatable_kill_unit,
    _is_self_recursion_return,
    has_own_target_spell,
    has_repeatable_engine,
    has_self_dies_value,
    has_self_etb_payload,
    has_self_etb_value,
    has_structural_big_hand_makers,
    has_structural_big_hand_matters,
    has_structural_coin_flip,
    has_structural_connive_makers,
    has_structural_dice_makers,
    has_structural_fight_makers,
    has_structural_group_hug_draw,
    has_structural_kill_engine,
    has_structural_meld_pair,
    has_structural_power_tap_engine,
    has_structural_theft_makers,
    has_value_tap_ability,
    is_clone_value_effect,
)

__all__ = [
    "ATTACK_TRIGGER_EVENTS",
    "CAST_TRIGGER_EVENTS",
    "ETB_TRIGGER_EVENTS",
    "PER_TURN_CONSTRAINT_TAGS",
    "RAID_CONDITION_TAGS",
    "SYNTHESIS_ARM_IDS",
    "_ANTHEM_PUMP_MODS",
    "_EACH_DRAW_RECIPIENTS",
    "_SPELLCAST_TRIGGER_RX",
    "SynthesizedNode",
    "_arm_ability_copy",
    "_arm_animate_artifact",
    "_arm_arcane_matters",
    "_arm_b13_node_anchor",
    "_arm_b13_raw_anchor",
    "_arm_base_power_ref_conjunctive",
    "_arm_base_pt_have_become",
    "_arm_base_pt_is_a_type_with",
    "_arm_base_pt_mass_where_x",
    "_arm_becomes_target_src_opp",
    "_arm_big_hand_makers",
    "_arm_big_hand_matters",
    "_arm_cant_block_grant",
    "_arm_celebration_matters",
    "_arm_clue_matters",
    "_arm_coin_flip_payoff",
    "_arm_color_change",
    "_arm_color_hoser",
    "_arm_connive_makers",
    "_arm_convoke_matters",
    "_arm_counter_distribute",
    "_arm_coven_matters",
    "_arm_creature_cast_trigger",
    "_arm_crimes_matter",
    "_arm_curse_matters",
    "_arm_dice_makers",
    "_arm_discover_makers",
    "_arm_dont_own",
    "_arm_evasion_self",
    "_arm_exalted_lone_attacker",
    "_arm_exhaust_matters",
    "_arm_extra_land_drop",
    "_arm_fight_makers",
    "_arm_firebending_matters",
    "_arm_flash_matters",
    "_arm_group_hug_draw",
    "_arm_historic_matters",
    "_arm_island_matters",
    "_arm_keyword_counter",
    "_arm_keyword_soup_same_true",
    "_arm_keyword_tribe",
    "_arm_keyword_tribe_any",
    "_arm_kill_engine",
    "_arm_land_creatures_dynamic_animate",
    "_arm_land_fetch_ramp",
    "_arm_legend_rule_off",
    "_arm_lessons_matter",
    "_arm_life_payment_insurance",
    "_arm_manland",
    "_arm_miracle_grant",
    "_arm_multicolor_matters",
    "_arm_noncombat_damage_payoff",
    "_arm_opponent_cast_matters",
    "_arm_opponent_counter_grant",
    "_arm_opponent_exile_matters",
    "_arm_outlaw_matters",
    "_arm_per_target_payoff",
    "_arm_poison_matters",
    "_arm_power_matters",
    "_arm_proliferate_matters",
    "_arm_proliferate_remove_cost",
    "_arm_pump_makers",
    "_arm_ramp_dropped_add_mana_clause",
    "_arm_ramp_grant_unimplemented_body",
    "_arm_sacrifice_protection",
    "_arm_self_counter_grow",
    "_arm_self_power_scale",
    "_arm_snow_matters",
    "_arm_spellcast_matters",
    "_arm_station_matters",
    "_arm_stax_taxes",
    "_arm_superfriends_matters",
    "_arm_suspect_matters",
    "_arm_suspend_matters",
    "_arm_symmetric_stax",
    "_arm_targeting_matters",
    "_arm_theft_makers",
    "_arm_token_subtype_own_ref",
    "_arm_tutor",
    "_arm_type_change",
    "_arm_type_matters",
    "_arm_typed_anthem_multi",
    "_arm_unspent_mana",
    "_arm_untap_engine",
    "_arm_vehicles_matter",
    "_arm_void_warp_makers",
    "_double_triggers_creature_dying",
    "_has_repeatable_kill_unit",
    "_has_structural_lifegain",
    "_is_creature_death_subject",
    "_is_death_payoff_effect",
    "_is_self_recursion_return",
    "_is_self_return_effect",
    "_is_shuffle_back_effect",
    "_iter_untap_targets",
    "_matches_add_mana_clause",
    "_matches_spellcast_idiom",
    "_mirror_token_maker_type_subjects",
    "_stax_structural_walk",
    "apply_tree_synthesis",
    "attack_raid_condition",
    "creature_death_condition",
    "has_attack_trigger",
    "has_attacking_you_effect",
    "has_filter_property",
    "has_gain_life_amplifier",
    "has_high_life_total_payoff",
    "has_life_gained_this_turn",
    "has_life_gained_trigger",
    "has_own_target_spell",
    "has_permanent_recast",
    "has_repeatable_engine",
    "has_self_dies_value",
    "has_self_etb_payload",
    "has_self_etb_value",
    "has_selfloss_engine",
    "has_structural_arcane",
    "has_structural_base_power_ref",
    "has_structural_base_pt_set",
    "has_structural_big_hand_makers",
    "has_structural_big_hand_matters",
    "has_structural_cant_block_grant",
    "has_structural_clue_matters",
    "has_structural_coin_flip",
    "has_structural_color_hoser",
    "has_structural_connive_makers",
    "has_structural_counter_distribute",
    "has_structural_creature_cast_trigger",
    "has_structural_crimes_matter",
    "has_structural_curse_matters",
    "has_structural_dice_makers",
    "has_structural_exert_matters",
    "has_structural_extra_land_drop",
    "has_structural_fight_makers",
    "has_structural_firebending_grant",
    "has_structural_group_hug_draw",
    "has_structural_keyword_counter",
    "has_structural_kill_engine",
    "has_structural_land_creatures_animate",
    "has_structural_legend_rule_off",
    "has_structural_lessons_matter",
    "has_structural_life_payment_insurance",
    "has_structural_manland",
    "has_structural_meld_pair",
    "has_structural_miracle_grant",
    "has_structural_multicolor_matters",
    "has_structural_opponent_cast_matters",
    "has_structural_opponent_counter_grant",
    "has_structural_outlaw",
    "has_structural_power_tap_engine",
    "has_structural_proliferate",
    "has_structural_pump_makers",
    "has_structural_ramp_grant_mana",
    "has_structural_self_counter_grow",
    "has_structural_snow_matters",
    "has_structural_spellcast",
    "has_structural_station_charge",
    "has_structural_station_reference",
    "has_structural_stax_taxes",
    "has_structural_superfriends",
    "has_structural_suspend_matters",
    "has_structural_symmetric_stax",
    "has_structural_targeting_matters",
    "has_structural_theft_makers",
    "has_structural_toughness_combat",
    "has_structural_tutor",
    "has_structural_type_change",
    "has_structural_unspent_mana",
    "has_structural_untap_engine",
    "has_structural_vehicles_matter",
    "has_trigger_draw_bleed",
    "has_value_tap_ability",
    "is_clone_value_effect",
    "mass_death_amount",
    "structural_keyword_subjects",
    "structural_land_fetch_split",
    "structural_token_maker_type_subjects",
    "structural_type_subjects",
    "structural_untap_scope",
    "structural_untap_subject",
    "synthesize_nodes",
]
