"""Stage-1 gate for the lossless phase-mirror substrate (ADR-0035).

The substrate is ADDITIVE — nothing in production reads it. These tests are the
shipped deliverable: the loud-on-bump drift detector plus the data-inference
codegen's correctness gates.

Two tiers:

* **Committed-fixture tests** (always run, CI-safe): exercise the generated
  mirror schema + a diverse real-card slice + the per-variant baseline, all
  committed under ``tests/fixtures/`` (regenerated by ``build-card-ir-substrate``).
* **Full-corpus tests** (skip unless the pinned 93MB ``card-data.json`` is
  present locally): re-infer + strict-load all 35,396 cards. These are the
  gated dev gate, never CI.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from mtg_utils import _phase
from mtg_utils._card_ir.metrics import compute_phase_variant_population
from mtg_utils._card_ir.mirror import (
    EFFECT_VARIANTS,
    ZERO_INSTANCE_EFFECTS,
    MirrorDriftError,
    find_ambiguous_fields,
    infer_schema,
    strict_load_card,
)
from mtg_utils._card_ir.mirror.build import (
    POPULATION_FIXTURE,
    SAMPLES_FIXTURE,
    SCHEMA_FIXTURE,
    fixtures_dir,
    load_committed_schema,
)

# ---------------------------------------------------------------------------
# fixtures / helpers
# ---------------------------------------------------------------------------


def _fixture(name: str) -> dict:
    path = fixtures_dir() / name
    if not path.exists():
        pytest.skip(f"{name} not built — run build-card-ir-substrate")
    return json.loads(path.read_text())


def _schema():
    if not (fixtures_dir() / SCHEMA_FIXTURE).exists():
        pytest.skip("phase_mirror_schema.json not built")
    return load_committed_schema()


def _samples() -> dict[str, dict]:
    return _fixture(SAMPLES_FIXTURE)["cards"]


def _card_data_records() -> list[dict]:
    path = _phase._card_data_path()
    if not path.exists():
        pytest.skip(f"pinned card-data absent at {path} (full-corpus gate)")
    data = json.loads(Path(path).read_text())
    return list(data.values()) if isinstance(data, dict) else list(data)


def _first_tagged(node, ckey="<root>"):
    """Return (parent_dict, ckey, tag) for the first tagged node found, or None."""
    if isinstance(node, dict):
        if isinstance(node.get("type"), str):
            return (node, ckey, node["type"])
        for k, v in node.items():
            hit = _first_tagged(v, k)
            if hit:
                return hit
    elif isinstance(node, list):
        for it in node:
            hit = _first_tagged(it, ckey)
            if hit:
                return hit
    return None


def _find_tagged_at(node, want_ckey, ckey="<root>"):
    """Return the first tagged node sitting at content_key ``want_ckey``."""
    if isinstance(node, dict):
        if isinstance(node.get("type"), str):
            if ckey == want_ckey:
                return node
            for k, v in node.items():
                if k != "type":
                    hit = _find_tagged_at(v, want_ckey, k)
                    if hit:
                        return hit
        else:
            for k, v in node.items():
                hit = _find_tagged_at(v, want_ckey, k)
                if hit:
                    return hit
    elif isinstance(node, list):
        for it in node:
            hit = _find_tagged_at(it, want_ckey, ckey)
            if hit:
                return hit
    return None


def _find_required(record, schema):
    """Find (tagged_node, ckey, tag, required_field) where the group has a
    non-``type`` required field — for the missing-required drift test."""
    found = []

    def walk(node, ckey):
        if isinstance(node, dict):
            tag = node.get("type")
            if isinstance(tag, str):
                grp = schema.tagged.get((ckey, tag))
                if grp:
                    req = [f for f in grp.required_fields() if f in node]
                    if req:
                        found.append((node, ckey, tag, req[0]))
                for k, v in node.items():
                    if k != "type":
                        walk(v, k)
            else:
                for k, v in node.items():
                    walk(v, k)
        elif isinstance(node, list):
            for it in node:
                walk(it, ckey)

    walk(record, "<root>")
    return found[0] if found else None


# ---------------------------------------------------------------------------
# roster sanity (no corpus / no fixtures needed)
# ---------------------------------------------------------------------------


def test_effect_roster_shape():
    assert len(EFFECT_VARIANTS) == 207
    assert len(ZERO_INSTANCE_EFFECTS) == 18
    assert set(EFFECT_VARIANTS) >= ZERO_INSTANCE_EFFECTS
    # the ADR's four named examples are in the closed-union arm
    for name in ("Cascade", "Exploit", "MiracleCast", "VentureInto"):
        assert name in ZERO_INSTANCE_EFFECTS


# ---------------------------------------------------------------------------
# GATE 1 — discriminator uniqueness
# ---------------------------------------------------------------------------


def test_discriminator_uniqueness_committed_schema():
    """Every (content_key, tag) group resolves to ONE payload schema — no field
    mixes ``tagged`` with another container kind (undecidable dispatch)."""
    schema = _schema()
    ambiguous = find_ambiguous_fields(schema)
    assert ambiguous == [], ambiguous


def test_discriminator_uniqueness_full_corpus():
    records = _card_data_records()
    schema = infer_schema(records, phase_tag=_phase.PHASE_TAG)
    ambiguous = find_ambiguous_fields(schema)
    assert ambiguous == [], ambiguous
    # the inference is a function: each (ckey, tag) -> exactly one GroupSchema
    assert len({(g.ckey, g.tag) for g in schema.tagged.values()}) == len(schema.tagged)


# ---------------------------------------------------------------------------
# GATE 2 — strict-load passes over the full corpus
# ---------------------------------------------------------------------------


def test_strict_load_full_corpus():
    records = _card_data_records()
    schema = infer_schema(records, phase_tag=_phase.PHASE_TAG)
    loaded = 0
    for rec in records:
        strict_load_card(rec, schema, build=False)
        loaded += 1
    assert loaded == len(records)
    assert loaded >= 35000


def test_strict_load_accepts_committed_samples():
    schema = _schema()
    for name, rec in _samples().items():
        strict_load_card(rec, schema, name=name, build=False)


# ---------------------------------------------------------------------------
# GATE 3 — injected drift fails loud
# ---------------------------------------------------------------------------


def test_injected_drift_unknown_field():
    schema = _schema()
    name, rec = next(iter(_samples().items()))
    drifted = copy.deepcopy(rec)
    node = _first_tagged(drifted)
    assert node is not None, "sample has no tagged node to mutate"
    node[0]["__phantom_field__"] = 1
    with pytest.raises(MirrorDriftError, match="unknown field"):
        strict_load_card(drifted, schema, name=name)


def test_injected_drift_renamed_tag():
    schema = _schema()
    name, rec = next(iter(_samples().items()))
    drifted = copy.deepcopy(rec)
    node = _first_tagged(drifted)
    assert node is not None
    node[0]["type"] = "__RenamedNonexistentVariant__"
    with pytest.raises(MirrorDriftError, match="unknown tagged node"):
        strict_load_card(drifted, schema, name=name)


def test_injected_drift_zero_instance_variant_closed_union():
    """Relocating a real effect-slot node onto a zero-instance Effect variant
    fails with the closed-union message on first emission."""
    schema = _schema()
    target = None
    for name, rec in _samples().items():
        if _find_tagged_at(rec, "effect"):
            target = (name, rec)
            break
    if target is None:
        pytest.skip("no effect-slot tagged node in samples")
    name, rec = target
    drifted = copy.deepcopy(rec)
    node = _find_tagged_at(drifted, "effect")
    node.clear()
    node["type"] = "Cascade"
    with pytest.raises(MirrorDriftError, match="zero-instance phase Effect"):
        strict_load_card(drifted, schema, name=name)


def test_injected_drift_missing_required_field():
    schema = _schema()
    target_name = None
    for name, rec in _samples().items():
        if _find_required(rec, schema):
            target_name = name
            break
    if target_name is None:
        pytest.skip("no required-field-bearing tagged node in samples")
    drifted = copy.deepcopy(_samples()[target_name])
    node, _ckey, _tag, required_field = _find_required(drifted, schema)
    node.pop(required_field)
    with pytest.raises(MirrorDriftError, match="missing required field"):
        strict_load_card(drifted, schema, name=target_name)


# ---------------------------------------------------------------------------
# GATE 4 — losslessness round-trip
# ---------------------------------------------------------------------------


def test_losslessness_roundtrip_samples():
    schema = _schema()
    for name, rec in _samples().items():
        loaded = strict_load_card(rec, schema, name=name, build=True)
        assert loaded is not None
        assert loaded.to_dict() == rec, f"{name} dropped a field on round-trip"


def test_losslessness_roundtrip_full_corpus():
    records = _card_data_records()
    schema = infer_schema(records, phase_tag=_phase.PHASE_TAG)
    # Round-trip a deterministic spread (every 1000th card) for speed.
    checked = 0
    for rec in records[::1000]:
        loaded = strict_load_card(rec, schema, build=True)
        assert loaded.to_dict() == rec
        checked += 1
    assert checked >= 30


# ---------------------------------------------------------------------------
# per-variant population baseline
# ---------------------------------------------------------------------------


def test_variant_population_committed_fixture():
    pop = _fixture(POPULATION_FIXTURE)
    population = pop["population"]
    assert len(population) == 207
    zeros = {n for n, c in population.items() if c == 0}
    assert zeros == set(ZERO_INSTANCE_EFFECTS)
    assert pop["distinct_variants_observed"] == 189
    assert pop["zero_instance_variants"] == 18
    assert pop["total_effect_nodes"] == sum(population.values())
    # the name grep must not have drifted from phase's enum
    assert pop["unknown_effect_slot_tags"] == {}


def test_variant_population_recompute_matches_corpus():
    records = _card_data_records()
    recomputed = compute_phase_variant_population(records)
    committed = _fixture(POPULATION_FIXTURE)
    assert recomputed["population"] == committed["population"]
    assert recomputed["total_effect_nodes"] == committed["total_effect_nodes"]
