"""Closed-union arm for phase's ``Effect`` enum (ADR-0035, Stage 1).

The ``Effect`` enum in phase's ``crates/engine/src/types/ability.rs`` declares
215 variants at the v0.15.0 pin (a cheap variant-**name** grep — names only,
never the Rust field shapes; 207 at v0.9.0 + 8 v0.15.0 additions). Of those,
**197 are witnessed** in the pinned v0.15.0 ``card-data.json`` at the canonical
effect slot (``ckey == "effect"``) and **18 emit zero instances** (Cascade,
Exploit, MiracleCast, VentureInto, …). The 18 get a closed-union arm: the strict
loader raises loudly on their *first emission* rather than letting an unwitnessed
variant slip in invisibly on a phase bump.

``EFFECT_VARIANTS`` is the full 215-name roster (the per-variant population
baseline seeds zeros from it). ``ZERO_INSTANCE_EFFECTS`` is the 18-name
closed-union subset. Both are data-grounded against v0.15.0 — regenerate via
``build-card-ir-substrate`` if the phase tag bumps.
"""

from __future__ import annotations

# The full phase ``Effect`` enum roster (207), grepped by name from ability.rs
# (`pub enum Effect { ... }`). Order preserved from the source enum.
EFFECT_VARIANTS: tuple[str, ...] = (
    "StartYourEngines",
    "ChangeSpeed",
    "DealDamage",
    "ApplyPostReplacementDamage",
    "EachDealsDamageEqualToPower",
    "Draw",
    "Pump",
    "PairWith",
    "Destroy",
    "Regenerate",
    "RemoveAllDamage",
    "Counter",
    "CounterAll",
    "Token",
    "GainLife",
    "LoseLife",
    "SetTapState",
    "RemoveCounter",
    "Sacrifice",
    "DiscardCard",
    "Mill",
    "Scry",
    "PumpAll",
    "DamageAll",
    "DamageEachPlayer",
    "DestroyAll",
    "ChangeZone",
    "ChangeZoneAll",
    "Dig",
    "GainControl",
    "GainControlAll",
    "ControlNextTurn",
    "Attach",
    "UnattachAll",
    "Surveil",
    "Fight",
    "Bounce",
    "BounceAll",
    "Explore",
    "ExploreAll",
    "Investigate",
    "Tribute",
    "TimeTravel",
    "BecomeMonarch",
    "NoOp",
    "Proliferate",
    "ProliferateTarget",
    "Populate",
    "Clash",
    "EndTheTurn",
    "EndCombatPhase",
    "Vote",
    "SeparateIntoPiles",
    "SwitchPT",
    "CopySpell",
    "EpicCopy",
    "CastCopyOfCard",
    "CopyTokenOf",
    "CreateTokenCopyFromPool",
    "Myriad",
    "Encore",
    "CombineHost",
    "ChooseAugmentAndCombineWithHost",
    "Meld",
    "ExileHaunting",
    "HideawayConceal",
    "CopyTokenBlockingAttacker",
    "BecomeCopy",
    "GainActivatedAbilitiesOfTarget",
    "ChooseCard",
    "PutCounter",
    "PutCounterAll",
    "MultiplyCounter",
    "DoublePT",
    "DoublePTAll",
    "MoveCounters",
    "Animate",
    "ReturnAsAura",
    "RegisterBending",
    "GenericEffect",
    "Cleanup",
    "Mana",
    "Discard",
    "Shuffle",
    "Transform",
    "SearchLibrary",
    "SearchOutsideGame",
    "RevealHand",
    "RevealFromHand",
    "Reveal",
    "RevealTop",
    "ExileTop",
    "TargetOnly",
    "Choose",
    "ChooseDamageSource",
    "Suspect",
    "Unsuspect",
    "Connive",
    "PhaseOut",
    "PhaseIn",
    "ForceBlock",
    "ForceAttack",
    "SolveCase",
    "BecomePrepared",
    "BecomeUnprepared",
    "BecomeSaddled",
    "SetClassLevel",
    "CreateDelayedTrigger",
    "AddTargetReplacement",
    "AddRestriction",
    "ReduceNextSpellCost",
    "GrantNextSpellAbility",
    "AddPendingETBCounters",
    "CreateEmblem",
    "PayCost",
    "CastFromZone",
    "FreeCastFromZones",
    "ExileResolvingSpellInsteadOfGraveyard",
    "PreventDamage",
    "CreateDamageReplacement",
    "LoseTheGame",
    "WinTheGame",
    "RollDie",
    "FlipCoin",
    "FlipCoins",
    "FlipCoinUntilLose",
    "RingTemptsYou",
    "VentureIntoDungeon",
    "VentureInto",
    "TakeTheInitiative",
    "Planeswalk",
    "OpenAttractions",
    "RollToVisitAttractions",
    "AssembleContraptions",
    "AssembleContraptionsFromRollDifference",
    "CrankContraptions",
    "ReassembleContraption",
    "AssembleContraptionOnSprocket",
    "ReassembleContraptionOnSprocket",
    "PutSticker",
    "ApplySticker",
    "ProcessRadCounters",
    "GrantCastingPermission",
    "ChooseFromZone",
    "ForEachCategoryExile",
    "ChooseObjectsIntoTrackedSet",
    "ChooseAndSacrificeRest",
    "Exploit",
    "GainEnergy",
    "GivePlayerCounter",
    "LoseAllPlayerCounters",
    "ExileFromTopUntil",
    "RevealUntil",
    "Discover",
    "Heist",
    "HeistExile",
    "Cascade",
    "Ripple",
    "MiracleCast",
    "MadnessCast",
    "PutAtLibraryPosition",
    "ChooseDrawnThisTurnPayOrTopdeck",
    "PutOnTopOrBottom",
    "GiftDelivery",
    "Goad",
    "GoadAll",
    "Detain",
    "SetRoomDoorLock",
    "ExchangeControl",
    "ChangeTargets",
    "Manifest",
    "ManifestDread",
    "Cloak",
    "TurnFaceUp",
    "ExtraTurn",
    "GrantExtraLoyaltyActivations",
    "SkipNextTurn",
    "SkipNextStep",
    "AdditionalPhase",
    "Double",
    "RuntimeHandled",
    "Incubate",
    "Amass",
    "Monstrosity",
    "Specialize",
    "Renown",
    "Bolster",
    "Adapt",
    "Learn",
    "Forage",
    "Harness",
    "CollectEvidence",
    "Endure",
    "BlightEffect",
    "Seek",
    "SetLifeTotal",
    "ExchangeLifeWithStat",
    "ExchangeLifeTotals",
    "SetDayNight",
    "GiveControl",
    "RemoveFromCombat",
    "Conjure",
    "ApplyPerpetual",
    "Intensify",
    "DraftFromSpellbook",
    "ChooseOneOf",
    "Unimplemented",
    # v0.15.0 additions (pin bump v0.9.0 → v0.15.0): 8 new Effect variants
    # witnessed in v0.15.0 card-data (ChaosEnsues 9, EachSourceDealsDamage 7,
    # TurnFaceDown 7, CreateDrawReplacement 3, PutChosenCounter 3, ChooseCounterKind
    # 2, CreatePlaneswalkReplacement 1, RememberCard 1). Appended (source enum order
    # unavailable without the v0.15.0 ability.rs); membership, not order, is what the
    # closed-union + population baseline read.
    "ChaosEnsues",
    "ChooseCounterKind",
    "CreateDrawReplacement",
    "CreatePlaneswalkReplacement",
    "EachSourceDealsDamage",
    "PutChosenCounter",
    "RememberCard",
    "TurnFaceDown",
)

# The name-known / shape-unknown variants: declared in phase's enum but with
# ZERO instances anywhere in v0.15.0 card-data. The closed-union arm fails loud
# on their first emission (see loader.strict_load_card).
ZERO_INSTANCE_EFFECTS: frozenset[str] = frozenset(
    {
        "ApplyPostReplacementDamage",
        "ApplySticker",
        "AssembleContraptionOnSprocket",
        "AssembleContraptionsFromRollDifference",
        "Cascade",
        "ChooseCard",
        "ChooseDamageSource",
        "Cleanup",
        "CrankContraptions",
        "CreateTokenCopyFromPool",
        "EpicCopy",
        "Exploit",
        "HeistExile",
        "MiracleCast",
        "ProcessRadCounters",
        "ReassembleContraptionOnSprocket",
        "Ripple",
        "VentureInto",
    }
)

# The content_key under which an ``Effect`` enum node sits in card-data.json.
# (Cost/Condition enums reuse some Effect *names* — e.g. ``Mana``, ``Discard`` —
# at other slots; the effect-population baseline counts only this slot.)
EFFECT_SLOT = "effect"
