"""Creature-subtype vocabulary + subject-resolution constants for signal extraction.

CREATURE_SUBTYPES is self-derived from Scryfall bulk type_lines (creature faces only,
split on // first so adventure/split spell faces never leak "sorcery"/"instant").
It is the allowlist that validates a captured tribal subject so junk captures (a clone
clause, a flavor noun) resolve to nothing rather than a false-positive kindred signal.

Regenerate after large set releases (the one-off: load bulk -> for creature faces,
split_type_line -> subtypes, lowercased, len>=3, alpha, minus NON_SUBJECT_WORDS).
New creature types are rare, so drift is slow.
"""

from __future__ import annotations

# Card-type / spell-type / noise nouns that must NEVER become a tribal subject —
# they fall through to the generic key instead (e.g. "creatures you control").
NON_SUBJECT_WORDS: frozenset[str] = frozenset(
    {
        "creature",
        "creatures",
        "permanent",
        "permanents",
        "token",
        "tokens",
        "spell",
        "spells",
        "card",
        "cards",
        "nonland",
        "noncreature",
        "nontoken",
        "color",
        "colors",
        "instant",
        "instants",
        "sorcery",
        "sorceries",
        "battle",
    }
)

# Card-type subjects we DO accept (type-matters card-type variant); these map to a
# card_type search rather than a kindred subtype search.
CARD_TYPE_SUBJECTS: frozenset[str] = frozenset(
    {
        "artifact",
        "enchantment",
        "land",
        "planeswalker",
        "equipment",
        "aura",
        "vehicle",
    }
)

# Irregular / partial-plural singularization. The (\w+?)s? capture can emit a partial
# plural ("Elve", "Dwarve") because the s? swallows the trailing s; map those to the
# real singular so flagship tribes (Magda->dwarf) don't silently drop.
IRREGULAR_SINGULAR: dict[str, str] = {
    "elves": "elf",
    "elve": "elf",
    "dwarves": "dwarf",
    "dwarve": "dwarf",
    "wolves": "wolf",
    "wolve": "wolf",
    "thieves": "thief",
    "thieve": "thief",
    "knives": "knife",
    "leaves": "leaf",
    "faeries": "faerie",
    "faerie": "faerie",
    "mice": "mouse",
    "wolfs": "wolf",
    "zombies": "zombie",
    "berries": "berry",
    "allies": "ally",
    "armies": "army",
    "fungi": "fungus",
    "djinn": "djinn",
    "efreet": "efreet",
    "sphinxes": "sphinx",
    "sphinx": "sphinx",
    "homunculi": "homunculus",
    "octopi": "octopus",
}

CREATURE_SUBTYPES: frozenset[str] = frozenset(
    {
        "advisor",
        "aetherborn",
        "alicorn",
        "alien",
        "ally",
        "angel",
        "antelope",
        "ape",
        "archer",
        "archon",
        "armadillo",
        "armored",
        "army",
        "art",
        "artificer",
        "artist",
        "assassin",
        "astartes",
        "athlete",
        "atog",
        "aurochs",
        "autobot",
        "avatar",
        "azra",
        "background",
        "baddest",
        "badger",
        "barbarian",
        "bard",
        "basilisk",
        "bat",
        "bear",
        "beast",
        "beaver",
        "beeble",
        "beholder",
        "berserker",
        "biggest",
        "bird",
        "bison",
        "boar",
        "book",
        "boxer",
        "brainiac",
        "bringer",
        "brushwagg",
        "bureaucrat",
        "camel",
        "capybara",
        "carrier",
        "cat",
        "centaur",
        "cephalid",
        "chameleon",
        "champion",
        "chef",
        "chicken",
        "child",
        "chimera",
        "citizen",
        "clamfolk",
        "cleric",
        "clown",
        "clue",
        "cockatrice",
        "construct",
        "cow",
        "coward",
        "coyote",
        "crab",
        "crocodile",
        "custodes",
        "cyberman",
        "cyborg",
        "cyclops",
        "dalek",
        "dauthi",
        "deer",
        "demigod",
        "demon",
        "designer",
        "detective",
        "devil",
        "dinosaur",
        "djinn",
        "doctor",
        "dog",
        "donkey",
        "dragon",
        "drake",
        "dreadnought",
        "drix",
        "drone",
        "druid",
        "dryad",
        "dwarf",
        "echidna",
        "efreet",
        "egg",
        "elder",
        "eldrazi",
        "elemental",
        "elephant",
        "elf",
        "elk",
        "elves",
        "employee",
        "equipment",
        "eternal",
        "etiquette",
        "eye",
        "faerie",
        "ferret",
        "fish",
        "flagbearer",
        "food",
        "forest",
        "fox",
        "fractal",
        "frog",
        "fungus",
        "gamer",
        "gamma",
        "gargoyle",
        "giant",
        "giraffe",
        "gith",
        "glimmer",
        "gnoll",
        "gnome",
        "goat",
        "goblin",
        "god",
        "golem",
        "gorgon",
        "grandchild",
        "gremlin",
        "griffin",
        "guest",
        "gus",
        "hag",
        "halfling",
        "hamster",
        "harpy",
        "hatificer",
        "hawk",
        "head",
        "hedgehog",
        "hellion",
        "hero",
        "hippo",
        "hippogriff",
        "homarid",
        "homunculus",
        "horror",
        "horse",
        "human",
        "hydra",
        "hyena",
        "illusion",
        "imp",
        "incarnation",
        "inhuman",
        "inkling",
        "inquisitor",
        "insect",
        "island",
        "jackal",
        "jellyfish",
        "judge",
        "juggernaut",
        "kangaroo",
        "kavu",
        "killbot",
        "kirin",
        "kithkin",
        "knight",
        "koala",
        "kobold",
        "kor",
        "kraken",
        "kree",
        "lady",
        "lamia",
        "lammasu",
        "lander",
        "leech",
        "lemur",
        "leviathan",
        "lhurgoyf",
        "licid",
        "lizard",
        "lobster",
        "locus",
        "lord",
        "mammoth",
        "manticore",
        "masticore",
        "mercenary",
        "merfolk",
        "metathran",
        "mime",
        "minion",
        "minotaur",
        "mite",
        "mole",
        "monger",
        "mongoose",
        "monk",
        "monkey",
        "moogle",
        "moonfolk",
        "mount",
        "mountain",
        "mouse",
        "mummy",
        "mutant",
        "myr",
        "mystic",
        "nastiest",
        "nautilus",
        "necron",
        "nephilim",
        "nightmare",
        "nightstalker",
        "ninja",
        "noble",
        "noggle",
        "nomad",
        "nymph",
        "octopus",
        "officer",
        "ogre",
        "ooze",
        "orc",
        "orgg",
        "otter",
        "ouphe",
        "oyster",
        "pangolin",
        "paratrooper",
        "peasant",
        "pegasus",
        "penguin",
        "performer",
        "pest",
        "phelddagrif",
        "phoenix",
        "phyrexian",
        "pilot",
        "pirate",
        "plant",
        "platypus",
        "pony",
        "porcupine",
        "possum",
        "praetor",
        "primarch",
        "processor",
        "proper",
        "rabbit",
        "raccoon",
        "ranger",
        "rat",
        "rebel",
        "reflection",
        "rhino",
        "rigger",
        "robot",
        "rogue",
        "sable",
        "saga",
        "salamander",
        "samurai",
        "sand",
        "saproling",
        "satyr",
        "scarecrow",
        "scientist",
        "scorpion",
        "scout",
        "seal",
        "serpent",
        "shade",
        "shaman",
        "shapeshifter",
        "shark",
        "sheep",
        "ship",
        "shrine",
        "siren",
        "skeleton",
        "skrull",
        "skunk",
        "slith",
        "sliver",
        "sloth",
        "slug",
        "snail",
        "snake",
        "soldier",
        "soltari",
        "sorcerer",
        "spawn",
        "specter",
        "spellshaper",
        "sphinx",
        "spider",
        "spike",
        "spirit",
        "splinter",
        "sponge",
        "spuzzem",
        "spy",
        "squid",
        "squirrel",
        "starfish",
        "surrakar",
        "survivor",
        "symbiote",
        "synth",
        "thalakos",
        "the",
        "thopter",
        "thrull",
        "tiefling",
        "time",
        "townsfolk",
        "toy",
        "treasure",
        "tree",
        "treefolk",
        "trilobite",
        "troll",
        "turtle",
        "tyranid",
        "unicorn",
        "utrom",
        "vampire",
        "vampyre",
        "varmint",
        "vedalken",
        "villain",
        "volver",
        "waiter",
        "wall",
        "walrus",
        "warlock",
        "warrior",
        "weasel",
        "weird",
        "werewolf",
        "whale",
        "wizard",
        "wolf",
        "wolverine",
        "wombat",
        "worm",
        "wraith",
        "wrestler",
        "wurm",
        "yeti",
        "zombie",
        "zonian",
        "zubera",
    }
)
