"""Cross-check deck-forge detector firings against phase-rs's parsed classification.

A **read-only audit harness** (like the cube/phase coverage gates — an analysis
tool, never part of the live build path). It surfaces where deck-forge's
hand-written signal detectors and phase-rs's deterministic oracle-text parser
*disagree* about a card, so disagreements can be triaged into detector gaps or
over-fires. It is a noisy second opinion, never ground truth.

phase-rs parses MTGJSON oracle text into a typed effect IR. Its ``card-data.json``
(generated by ``playtest-install-phase`` → ``scripts/gen-card-data.sh``) records,
per face, the parsed ``keywords`` plus ``abilities`` (each carrying an ``effect``
whose ``type`` is an Effect discriminant), ``triggers`` (each a ``mode``
TriggerMode), ``static_abilities`` (each a ``mode`` StaticMode), and
``replacements``. We project each face to a normalized tag set and diff it against
the signal keys ``extract_signals`` fires on the same card, joined by Scryfall
``oracle_id`` (present on both sides).

Two caveats shape the design:

1. phase's parse is deterministic but **incomplete** — a face whose
   ``parse_warnings`` is non-empty punted on some text, so phase's silence there
   is a parse gap, not a real disagreement (segregated via ``include_low_confidence``).

2. phase's IR describes what a card *does*; deck-forge's ``*_matters`` lanes
   describe synergy **payoffs** ("whenever X happens, …"). So the ``CROSSWALK``
   maps *payoff* lanes to phase **triggers** (the "whenever" shape) and *doer*
   lanes (token_maker, direct_damage, untap_engine) to phase **effects**. Mixing
   the two floods PHASE_ONLY with "card does X but isn't a payoff for X" noise.

Three verdicts per (card, lane):

  * ``BOTH``          — detector fires & phase corroborates  → agreement
  * ``DETECTOR_ONLY`` — detector fires, phase silent          → over-fire OR phase gap
  * ``PHASE_ONLY``    — phase corroborates, detector silent   → candidate detector gap
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable, Iterable
from pathlib import Path

from mtg_utils._deck_forge._ir_lookup import ir_for
from mtg_utils._deck_forge.signals import extract_signals_hybrid

# ── phase enum vocabularies (harvested from phase v0.1.19 source) ─────────────
# Variant names verbatim; matched case-insensitively after normalization, so
# phase's serde casing (PascalCase today) does not matter. EffectKind mirrors the
# Effect enum 1:1 per phase's own doc comment, so it covers every effect tag.
_EFFECT_KINDS = [
    "StartYourEngines",
    "IncreaseSpeed",
    "DealDamage",
    "Draw",
    "Pump",
    "Destroy",
    "Counter",
    "Token",
    "GainLife",
    "LoseLife",
    "Tap",
    "Untap",
    "AddCounter",
    "RemoveCounter",
    "Sacrifice",
    "DiscardCard",
    "Mill",
    "Scry",
    "PumpAll",
    "DamageAll",
    "DamageEachPlayer",
    "DestroyAll",
    "TapAll",
    "UntapAll",
    "ChangeZone",
    "ChangeZoneAll",
    "Dig",
    "GainControl",
    "ControlNextTurn",
    "Attach",
    "AttachAll",
    "Surveil",
    "Fight",
    "Bounce",
    "Explore",
    "ExploreAll",
    "Investigate",
    "Tribute",
    "TimeTravel",
    "BecomeMonarch",
    "Proliferate",
    "Populate",
    "Clash",
    "SwitchPT",
    "CopySpell",
    "CopyTokenOf",
    "BecomeCopy",
    "ChooseCard",
    "PutCounter",
    "PutCounterAll",
    "MultiplyCounter",
    "DoublePT",
    "DoublePTAll",
    "MoveCounters",
    "Animate",
    "RegisterBending",
    "GenericEffect",
    "Cleanup",
    "Mana",
    "Discard",
    "Shuffle",
    "SearchLibrary",
    "ExileTop",
    "TargetOnly",
    "Choose",
    "Suspect",
    "Connive",
    "PhaseOut",
    "PhaseIn",
    "ForceBlock",
    "SolveCase",
    "BecomePrepared",
    "BecomeUnprepared",
    "SetClassLevel",
    "CreateDelayedTrigger",
    "AddRestriction",
    "ReduceNextSpellCost",
    "GrantNextSpellAbility",
    "AddPendingETBCounters",
    "CreateEmblem",
    "PayCost",
    "CastFromZone",
    "PreventDamage",
    "Regenerate",
    "LoseTheGame",
    "WinTheGame",
    "RollDie",
    "FlipCoin",
    "FlipCoins",
    "FlipCoinUntilLose",
    "RingTemptsYou",
    "VentureIntoDungeon",
    "VentureInto",
    "TakeTheInitiative",
    "GrantCastingPermission",
    "ChooseFromZone",
    "ChooseAndSacrificeRest",
    "Exploit",
    "GainEnergy",
    "GivePlayerCounter",
    "LoseAllPlayerCounters",
    "ExileFromTopUntil",
    "RevealUntil",
    "Discover",
    "Cascade",
    "MiracleCast",
    "MadnessCast",
    "PutAtLibraryPosition",
    "PutOnTopOrBottom",
    "GiftDelivery",
    "Goad",
    "Detain",
    "ExchangeControl",
    "ChangeTargets",
    "Incubate",
    "Amass",
    "Monstrosity",
    "Bolster",
    "Adapt",
    "Manifest",
    "ManifestDread",
    "ExtraTurn",
    "SkipNextTurn",
    "AdditionalCombatPhase",
    "Double",
    "RuntimeHandled",
    "Learn",
    "Forage",
    "CollectEvidence",
    "Endure",
    "BlightEffect",
    "Seek",
    "SetLifeTotal",
    "SetDayNight",
    "GiveControl",
    "RemoveFromCombat",
    "Conjure",
    "ChooseOneOf",
    "Unimplemented",
    "Equip",
    "Crew",
    "Station",
    "Saddle",
    "Reveal",
    "Transform",
    "TurnFaceUp",
    "DayTimeChange",
]

_TRIGGER_MODES = [
    "ChangesZone",
    "ChangesZoneAll",
    "ChangesController",
    "LeavesBattlefield",
    "DamageDone",
    "DamageDoneOnce",
    "DamageAll",
    "DamageDealtOnce",
    "DamageDoneOnceByController",
    "DamageReceived",
    "DamagePreventedOnce",
    "ExcessDamage",
    "ExcessDamageAll",
    "SpellCast",
    "SpellCopy",
    "SpellCastOrCopy",
    "AbilityCast",
    "AbilityResolves",
    "AbilityTriggered",
    "SpellAbilityCast",
    "SpellAbilityCopy",
    "Countered",
    "Attacks",
    "AttackersDeclared",
    "YouAttack",
    "AttackersDeclaredOneTarget",
    "AttackerBlocked",
    "AttackerBlockedOnce",
    "AttackerBlockedByCreature",
    "AttackerUnblocked",
    "AttackerUnblockedOnce",
    "Blocks",
    "BlockersDeclared",
    "BecomesBlocked",
    "CounterAdded",
    "CounterAddedOnce",
    "CounterAddedAll",
    "CounterPlayerAddedAll",
    "CounterTypeAddedAll",
    "CounterRemoved",
    "CounterRemovedOnce",
    "Sacrificed",
    "SacrificedOnce",
    "Destroyed",
    "Taps",
    "TapsForMana",
    "TapAll",
    "Untaps",
    "UntapAll",
    "BecomesTarget",
    "BecomesTargetOnce",
    "Drawn",
    "Discarded",
    "DiscardedAll",
    "Milled",
    "MilledOnce",
    "MilledAll",
    "Exiled",
    "Revealed",
    "Shuffled",
    "LifeGained",
    "LifeLost",
    "LifeLostAll",
    "PayLife",
    "PayCumulativeUpkeep",
    "PayEcho",
    "TokenCreated",
    "TokenCreatedOnce",
    "TurnFaceUp",
    "Transformed",
    "Phase",
    "PhaseIn",
    "PhaseOut",
    "PhaseOutAll",
    "TurnBegin",
    "NewGame",
    "BecomeMonarch",
    "TakesInitiative",
    "LosesGame",
    "Championed",
    "Exerted",
    "Crewed",
    "Crews",
    "Saddled",
]

_STATIC_MODES = [
    "Continuous",
    "CantAttack",
    "CantBlock",
    "CantAttackOrBlock",
    "CantBeTargeted",
    "CantBeCast",
    "CantBeActivated",
    "CantSearchLibrary",
    "CastWithFlash",
    "CastWithKeyword",
    "ReduceCost",
    "ReduceAbilityCost",
    "RaiseCost",
    "CantGainLife",
    "CantLoseLife",
    "MustAttack",
    "MustBlock",
    "CantDraw",
    "DoubleTriggers",
    "IgnoreHexproof",
    "ExtraBlockers",
    "RevealTopOfLibrary",
    "GraveyardCastPermission",
    "CastFromHandFree",
    "CantBeCountered",
    "CantBeCopied",
    "CantEnterBattlefieldFrom",
    "CantCastFrom",
    "CantCastDuring",
    "PerTurnCastLimit",
    "PerTurnDrawLimit",
    "SuppressTriggers",
    "CantBeBlocked",
    "CantBeBlockedExceptBy",
    "CantBeBlockedBy",
    "Protection",
    "Indestructible",
    "CantBeDestroyed",
    "FlashBack",
    "Shroud",
    "Hexproof",
    "Vigilance",
    "Menace",
    "Reach",
    "Flying",
    "Trample",
    "Deathtouch",
    "Lifelink",
    "CantTap",
    "CantUntap",
    "MustBeBlocked",
    "CantAttackAlone",
    "CantBlockAlone",
    "MayLookAtTopOfLibrary",
    "MayChooseNotToUntap",
    "AdditionalLandDrop",
    "EmblemStatic",
    "BlockRestriction",
    "NoMaximumHandSize",
    "MaximumHandSize",
    "MayPlayAdditionalLand",
]


def _norm(token: str) -> str:
    """Lowercase + strip non-alphanumerics, so ``DealDamage``/``deal_damage`` match."""
    return re.sub(r"[^a-z0-9]", "", token.lower())


_EFFECT_VOCAB = frozenset(_norm(t) for t in _EFFECT_KINDS)
_TRIGGER_VOCAB = frozenset(_norm(t) for t in _TRIGGER_MODES)
_STATIC_VOCAB = frozenset(_norm(t) for t in _STATIC_MODES)

_PHASE_ABILITY_ARRAYS = ("abilities", "triggers", "static_abilities", "replacements")


def _collect_tokens(node: object, out: set[str]) -> None:
    """Collect candidate enum discriminants from a parsed-ability subtree.

    Two sources, chosen to dodge struct field-name collisions (e.g. a ``"mana"``
    cost key vs. the ``Mana`` EffectKind):

      * every string leaf — captures ``tag="type"`` discriminants (the value of
        ``type``/``mode``/``kind``) and unit-variant strings; and
      * the single key of an externally-tagged enum dict — a one-key dict whose
        key is PascalCase, e.g. ``{"ReduceCost": {...}}``.

    Multi-key struct keys are never collected, so snake_case field names can't
    masquerade as mechanic tags.
    """
    if isinstance(node, str):
        out.add(node)
    elif isinstance(node, dict):
        if len(node) == 1:
            ((key, value),) = node.items()
            if isinstance(key, str) and key[:1].isupper():
                out.add(key)
            _collect_tokens(value, out)
        else:
            for value in node.values():
                _collect_tokens(value, out)
    elif isinstance(node, list):
        for item in node:
            _collect_tokens(item, out)


def phase_tags(record: dict) -> frozenset[str]:
    """Project a phase ``card-data.json`` face record to namespaced mechanic tags.

    Returns a set of ``effect:<x>`` / ``trigger:<x>`` / ``static:<x>`` / ``kw:<x>``
    tags (one token may yield several namespaces, e.g. ``TapAll`` is both an
    effect and a trigger). Tokens outside the baked phase vocabularies are dropped
    as structural noise.
    """
    raw: set[str] = set()
    for array in _PHASE_ABILITY_ARRAYS:
        _collect_tokens(record.get(array) or [], raw)

    tags: set[str] = set()
    for token in raw:
        norm = _norm(token)
        if norm in _EFFECT_VOCAB:
            tags.add(f"effect:{norm}")
        if norm in _TRIGGER_VOCAB:
            tags.add(f"trigger:{norm}")
        if norm in _STATIC_VOCAB:
            tags.add(f"static:{norm}")

    for keyword in record.get("keywords") or []:
        if isinstance(keyword, str):
            tags.add(f"kw:{_norm(keyword)}")
        elif isinstance(keyword, dict) and keyword:
            first_key = next(iter(keyword))
            if isinstance(first_key, str):
                tags.add(f"kw:{_norm(first_key)}")
    return frozenset(tags)


# ── the crosswalk: deck-forge signal lane → phase tags that corroborate it ────
# The editable heart of the tool. Payoff ("*_matters") lanes map to phase
# TRIGGERS (the "whenever X" shape); doer lanes map to phase EFFECTS. Keys MUST
# match real ``Signal.key`` values emitted by signals.py — a lane that only ever
# shows up as PHASE_ONLY (never both/detector_only across a real corpus) is a
# sign of a typo'd or retired key here.
CROSSWALK: dict[str, frozenset[str]] = {
    # ── doer lanes → phase effects ──
    "token_maker": frozenset(
        {
            "effect:token",
            "effect:populate",
            "effect:investigate",
            "effect:incubate",
            "effect:amass",
            "effect:conjure",
            "effect:manifest",
            "effect:manifestdread",
        }
    ),
    "direct_damage": frozenset(
        {"effect:dealdamage", "effect:damageall", "effect:damageeachplayer"}
    ),
    "untap_engine": frozenset({"effect:untap", "effect:untapall"}),
    # _matters sweep (ADR-0034): effect:proliferate is the DOER crosswalk — it maps
    # to the maker arm (proliferate_makers), not the cares-about payoff lane.
    "proliferate_makers": frozenset({"effect:proliferate"}),
    "topdeck_selection": frozenset(
        {"effect:scry", "effect:surveil", "effect:dig", "effect:explore"}
    ),
    "topdeck_stack": frozenset(
        {"effect:putontoporbottom", "effect:putatlibraryposition"}
    ),
    "gain_control": frozenset(
        {"effect:gaincontrol", "effect:controlnextturn", "effect:givecontrol"}
    ),
    "theft_makers": frozenset(
        {"effect:gaincontrol", "effect:controlnextturn", "effect:exchangecontrol"}
    ),
    # blink/reanimation both surface as a zone change in phase's IR; loose, so
    # expect noise — useful only as a coarse "touches the change-zone machinery".
    "blink_flicker": frozenset({"effect:changezone", "effect:changezoneall"}),
    "self_blink": frozenset({"effect:changezone"}),
    "reanimator": frozenset({"effect:changezone"}),
    "cheat_into_play": frozenset({"effect:changezone", "effect:castfromzone"}),
    # ── payoff ("*_matters") lanes → phase triggers ──
    "lifegain_matters": frozenset({"trigger:lifegained"}),
    "spellcast_matters": frozenset(
        {"trigger:spellcast", "trigger:spellcastorcopy", "trigger:spellcopy"}
    ),
    "discard_matters": frozenset(
        {
            "trigger:discarded",
            "trigger:discardedall",
            "effect:discard",
            "effect:discardcard",
        }
    ),
    # phase has no "Dies" trigger mode — a "when ~ dies" trigger surfaces as a
    # ChangesZone (battlefield→graveyard) and death routes as Destroyed /
    # Sacrificed / LeavesBattlefield. Mapping to the literal `trigger:dies` (which
    # no projection ever emits) silently matched nothing.
    "graveyard_matters": frozenset(
        {
            "trigger:milled",
            "trigger:milledall",
            "trigger:changeszone",
            "trigger:leavesbattlefield",
            "trigger:destroyed",
            "trigger:sacrificed",
            "effect:mill",
        }
    ),
    "self_death_payoff": frozenset(
        {
            "trigger:changeszone",
            "trigger:leavesbattlefield",
            "trigger:destroyed",
            "trigger:sacrificed",
        }
    ),
    "combat_damage_to_opp": frozenset({"trigger:damagedone"}),
    "blocked_matters": frozenset(
        {"trigger:attackerblocked", "trigger:becomesblocked", "trigger:blocks"}
    ),
    # _matters sweep (ADR-0034): the +1/+1 split. The placement/double effects are the
    # MAKER arm (deck-forge fires plus_one_makers); the counter MOVE and the
    # counter-added TRIGGER are the PAYOFF arm (plus_one_matters — relocating / caring,
    # not creating).
    "plus_one_makers": frozenset(
        {
            "effect:addcounter",
            "effect:putcounter",
            "effect:putcounterall",
            "effect:multiplycounter",
        }
    ),
    "plus_one_matters": frozenset(
        {
            "effect:movecounters",
            "trigger:counteradded",
            "trigger:counteraddedall",
        }
    ),
    "self_counter_grow": frozenset({"effect:addcounter", "effect:putcounter"}),
}


BOTH = "both"
DETECTOR_ONLY = "detector_only"
PHASE_ONLY = "phase_only"


def detector_lanes(card: dict) -> frozenset[str]:
    """The set of signal keys deck-forge's detectors fire on ``card``."""
    return frozenset(s.key for s in extract_signals_hybrid(card, ir_for(card)))


def classify_card(
    fired: Iterable[str],
    tags: Iterable[str],
    crosswalk: dict[str, frozenset[str]] = CROSSWALK,
) -> dict[str, str]:
    """Verdict per crosswalk lane that either side touches (others omitted)."""
    fired_set = set(fired)
    tag_set = set(tags)
    out: dict[str, str] = {}
    for lane, phase_corroborators in crosswalk.items():
        fires = lane in fired_set
        corroborated = bool(tag_set & phase_corroborators)
        if fires and corroborated:
            out[lane] = BOTH
        elif fires:
            out[lane] = DETECTOR_ONLY
        elif corroborated:
            out[lane] = PHASE_ONLY
    return out


def crosscheck_corpus(
    cards: Iterable[dict],
    phase_index: dict[str, dict],
    *,
    crosswalk: dict[str, frozenset[str]] = CROSSWALK,
    include_low_confidence: bool = True,
    example_cap: int = 8,
    extract: Callable[[dict], Iterable[str]] = detector_lanes,
) -> dict:
    """Join ``cards`` to ``phase_index`` by ``oracle_id`` and tally agreement.

    ``phase_index`` maps ``oracle_id`` → phase face record (see ``load_phase_index``).
    Returns a structured report: per-lane both/detector_only/phase_only counts with
    capped example card names, join/skip stats, the detector lanes that fired but
    aren't in the crosswalk (cross-check blind spots), and the phase tags that
    corroborate no lane (candidates to grow the crosswalk).
    """
    mapped_tags: set[str] = set().union(*crosswalk.values()) if crosswalk else set()
    lanes: dict[str, dict] = {}
    unmapped_detector: dict[str, int] = {}
    unmapped_phase: dict[str, int] = {}
    joined = 0
    skipped = {"no_oracle_id": 0, "not_in_phase": 0, "low_confidence": 0}

    for card in cards:
        oracle_id = card.get("oracle_id")
        if not oracle_id:
            skipped["no_oracle_id"] += 1
            continue
        record = phase_index.get(oracle_id)
        if record is None:
            skipped["not_in_phase"] += 1
            continue
        if not include_low_confidence and record.get("parse_warnings"):
            skipped["low_confidence"] += 1
            continue

        joined += 1
        fired = set(extract(card))
        tags = phase_tags(record)
        name = card.get("name", "")

        for lane, verdict in classify_card(fired, tags, crosswalk).items():
            tally = lanes.setdefault(
                lane, {BOTH: 0, DETECTOR_ONLY: 0, PHASE_ONLY: 0, "examples": {}}
            )
            tally[verdict] += 1
            examples = tally["examples"].setdefault(verdict, [])
            if len(examples) < example_cap and name not in examples:
                examples.append(name)

        for lane in fired:
            if lane not in crosswalk:
                unmapped_detector[lane] = unmapped_detector.get(lane, 0) + 1
        for tag in tags:
            if tag not in mapped_tags:
                unmapped_phase[tag] = unmapped_phase.get(tag, 0) + 1

    return {
        "lanes": lanes,
        "joined": joined,
        "skipped": skipped,
        "unmapped_detector_lanes": unmapped_detector,
        "unmapped_phase_tags": unmapped_phase,
    }


def load_phase_index(path: str | Path | None = None) -> dict[str, dict]:
    """Build an ``oracle_id`` → face-record index from phase's ``card-data.json``.

    Defaults to the path our ``playtest-install-phase`` writes. ``card-data.json``
    is keyed by lowercased face name; we re-key by ``scryfall_oracle_id`` (first
    face wins, so multi-face cards resolve to their front face).
    """
    if path is None:
        from mtg_utils import _phase

        path = _phase._card_data_path()  # noqa: SLF001 — canonical phase card-data path
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"phase card-data.json not found at {path}. "
            "Run `playtest-install-phase` to generate it."
        )
    data = json.loads(path.read_text())
    records = data.values() if isinstance(data, dict) else data
    index: dict[str, dict] = {}
    for record in records:
        oracle_id = record.get("scryfall_oracle_id")
        if oracle_id:
            index.setdefault(oracle_id, record)
    return index


def load_cards(path: str | Path) -> list[dict]:
    """Load a card corpus from JSON: a plain list of card dicts, or a parsed-deck
    dict (``commanders`` / ``cards`` / ``sideboard``) which is flattened."""
    data = json.loads(Path(path).read_text())
    if isinstance(data, list):
        return data
    cards: list[dict] = []
    for section in ("commanders", "cards", "sideboard"):
        cards.extend(data.get(section) or [])
    return cards


def render_report(report: dict) -> str:
    """Render a cross-check report as a markdown digest, lanes ordered by the
    actionable signal (most disagreement first)."""
    lines: list[str] = ["# phase-rs ↔ deck-forge detector cross-check", ""]
    skipped = report["skipped"]
    lines.append(
        f"Joined **{report['joined']}** cards by oracle_id "
        f"(skipped: {skipped['no_oracle_id']} no-oracle_id, "
        f"{skipped['not_in_phase']} not-in-phase, "
        f"{skipped['low_confidence']} low-confidence parse).",
    )
    lines.append("")

    lanes = report["lanes"]
    if lanes:
        lines += [
            "## Lanes (by disagreement)",
            "",
            "| lane | both | detector-only | phase-only |",
            "| --- | ---: | ---: | ---: |",
        ]
        ordered = sorted(
            lanes.items(),
            key=lambda kv: (kv[1][DETECTOR_ONLY] + kv[1][PHASE_ONLY], kv[1][BOTH]),
            reverse=True,
        )
        for lane, tally in ordered:
            both, det, phase = tally[BOTH], tally[DETECTOR_ONLY], tally[PHASE_ONLY]
            lines.append(f"| {lane} | {both} | {det} | {phase} |")
        lines.append("")
        # Per-lane examples for the disagreement buckets (the triage worklist).
        for lane, tally in ordered:
            for bucket in (PHASE_ONLY, DETECTOR_ONLY):
                names = tally["examples"].get(bucket) or []
                if names:
                    lines.append(f"- **{lane}** {bucket}: {', '.join(names)}")
        lines.append("")

    unmapped_det = report["unmapped_detector_lanes"]
    if unmapped_det:
        lines.append("## Detector lanes with no crosswalk mapping (blind spots)")
        lines.append("")
        for lane, count in sorted(unmapped_det.items(), key=lambda kv: -kv[1]):
            lines.append(f"- {lane}: {count}")
        lines.append("")

    unmapped_phase = report["unmapped_phase_tags"]
    if unmapped_phase:
        lines.append("## Top phase tags mapping to no lane (grow the crosswalk)")
        lines.append("")
        for tag, count in sorted(unmapped_phase.items(), key=lambda kv: -kv[1])[:25]:
            lines.append(f"- {tag}: {count}")
        lines.append("")

    return "\n".join(lines)


def _ensure_ir() -> None:
    """Best-effort Card IR sidecar build so a standalone crosscheck run is
    Seam-B-native (ADR-0039 task #80 step 4) — this CLI never launches
    through ``default_state`` (which already ensures it), so without this
    call a fresh cache directory would leave every ``ir_for`` lookup below
    returning ``None``, silently degrading the ``ir_for``-informed detector
    lanes to their regex reads. Called BEFORE the first ``ir_for`` so the
    memoized index isn't poisoned with a pre-build ``None``. Non-fatal — a
    build failure degrades to the regex path, matching the no-sidecar
    fallback every other Seam-B consumer already has."""
    import sys

    from mtg_utils._deck_forge.production import ensure_card_ir

    try:
        ensure_card_ir()
    except (OSError, ValueError) as exc:  # corrupt/locked phase data → degrade
        print(
            f"deck-forge-phase-crosscheck: Card IR unavailable ({exc}); "
            "using regex path.",
            file=sys.stderr,
        )


def main(argv: list[str] | None = None) -> int:
    """CLI: ``python -m mtg_utils._deck_forge.phase_crosscheck <cards.json> [opts]``."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Cross-check deck-forge detector firings against phase-rs's "
        "parsed card classification (read-only audit).",
    )
    parser.add_argument(
        "cards",
        help="JSON: a list of hydrated card dicts, or a parsed-deck dict.",
    )
    parser.add_argument(
        "--phase-data",
        default=None,
        help="Path to phase card-data.json (default: the playtest-install location).",
    )
    parser.add_argument(
        "--include-low-confidence",
        action="store_true",
        help="Include faces phase flagged with parse_warnings (default: excluded).",
    )
    parser.add_argument(
        "--json", action="store_true", help="Emit the raw report as JSON."
    )
    args = parser.parse_args(argv)

    _ensure_ir()  # build the sidecar on first run, BEFORE the first ir_for
    try:
        phase_index = load_phase_index(args.phase_data)
    except FileNotFoundError as exc:
        print(str(exc))
        return 1

    cards = load_cards(args.cards)
    report = crosscheck_corpus(
        cards,
        phase_index,
        include_low_confidence=args.include_low_confidence,
    )
    print(json.dumps(report, indent=2) if args.json else render_report(report))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
